### ISSUE TITLE
google_compute_health_check "only one of" error

### ISSUE THREAD

**Issue by juan-vg** [terraform-google-modules/terraform-google-lb-http#100]
## Environment

    Terraform: v0.12.19
    terraform-google-lb-http: 4.0.0

#### Error started happening: May 5th 2020 - 07:00 GMT

    google-beta provider: 3.20

#### Last time working: May 4th 2020 - 16:00 GMT

    google-beta provider: 3.19

## Error output

``` terraform

Error: "http2_health_check": only one of `http2_health_check,http_health_check,https_health_check,ssl_health_check,tcp_health_check` can be specified, but `http2_health_check,http_health_check,https_health_check` were specified.

  on .terraform/modules/lb_https/terraform-google-lb-http-4.0.0/main.tf line 132, in resource "google_compute_health_check" "default":
 132: resource "google_compute_health_check" "default" {



Error: "http_health_check": only one of `http2_health_check,http_health_check,https_health_check,ssl_health_check,tcp_health_check` can be specified, but `http2_health_check,http_health_check,https_health_check` were specified.

  on .terraform/modules/lb_https/terraform-google-lb-http-4.0.0/main.tf line 132, in resource "google_compute_health_check" "default":
 132: resource "google_compute_health_check" "default" {



Error: "tcp_health_check": only one of `http2_health_check,http_health_check,https_health_check,ssl_health_check,tcp_health_check` can be specified, but `http2_health_check,http_health_check,https_health_check` were specified.

  on .terraform/modules/lb_https/terraform-google-lb-http-4.0.0/main.tf line 132, in resource "google_compute_health_check" "default":
 132: resource "google_compute_health_check" "default" {


Error: "https_health_check": only one of `http2_health_check,http_health_check,https_health_check,ssl_health_check,tcp_health_check` can be specified, but `http2_health_check,http_health_check,https_health_check` were specified.

  on .terraform/modules/lb_https/terraform-google-lb-http-4.0.0/main.tf line 132, in resource "google_compute_health_check" "default":
 132: resource "google_compute_health_check" "default" {

```

## Workaround
Download module to project, and edit the [main.tf file](https://github.com/terraform-google-modules/terraform-google-lb-http/blob/release-v4.0.0/main.tf#L132).

As long as we are using "http_health_check", on the resource "google_compute_health_check" remove the dynamic "https_health_check" and "http2_health_check" blocks.

```diff
diff --git a/main.tf b/main.tf
index bc609ad..913cdc4 100644
--- a/main.tf
+++ b/main.tf
@@ -155,38 +155,6 @@ resource "google_compute_health_check" "default" {
     }
   }

-  dynamic "https_health_check" {
-    for_each = each.value["protocol"] == "HTTPS" ? [
-      {
-        host         = lookup(each.value["health_check"], "host", null)
-        request_path = lookup(each.value["health_check"], "request_path", null)
-        port         = lookup(each.value["health_check"], "port", null)
-      }
-    ] : []
-
-    content {
-      host         = lookup(https_health_check.value, "host", null)
-      request_path = lookup(https_health_check.value, "request_path", null)
-      port         = lookup(https_health_check.value, "port", null)
-    }
-  }
-
-  dynamic "http2_health_check" {
-    for_each = each.value["protocol"] == "HTTP2" ? [
-      {
-        host         = lookup(each.value["health_check"], "host", null)
-        request_path = lookup(each.value["health_check"], "request_path", null)
-        port         = lookup(each.value["health_check"], "port", null)
-      }
-    ] : []
-
-    content {
-      host         = lookup(http2_health_check.value, "host", null)
-      request_path = lookup(http2_health_check.value, "request_path", null)
-      port         = lookup(http2_health_check.value, "port", null)
-    }
-  }
-
 }

 resource "google_compute_firewall" "default-hc" {
```

### Possible explanation

Seems since latest google-beta provider's version the "google_compute_health_check" parameter has been enforced to accept one (and only one) kind of health_check per backend. 

Even though each dynamic block is conditioned by a for_each clause, looks like the component is being generated anyways

**Comment by morgante** [comment]
@juan-vg Would you mind filing an issue on the provider? It should be fixed there.

**Comment by juan-vg** [comment]
@morgante From my point of view the problem is not the provider, as they have warned about this on [their upgrade guide.](https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#resource-google_compute_health_check)

Is this module who is not properly working

**Comment by morgante** [comment]
I'm quite confident this is a provider bug. The module was working before and continues to generate the correct config. They made a breaking change which caused this to stop working and can only be fixed on their end.

As you can see, we're already dynamically generating the correct config (only one kind at a time). This needs to be fixed on the provider.

**Comment by juan-vg** [comment]
@morgante I've set a fixed provider version and the error is still there. I can understand this can come directly from GCP, but the provider seems to not be the guilty one. 

Moreover, if you're dynamically generating the correct config, why when I remove a piece of code from this module the error disappears? What I remove is the part where extra health_checks are being generated, so looks like the configuration is not that correct

**Comment by morgante** [comment]
Your own bug report state this issue only occurs on the 3.20 provider. It's self-evidently a provider issue.

The reason your workaround work is that you simply *entirely removed* dynamic blocks which _you_ happen to not be using. We cannot remove those blocks entirely because other people's use case requires them.

The blocks are correctly generated. The issue is the provider is attempting to validate as though *all* blocks are being set, even though in reality only 1 is generated at a time.

Once again, there is absolutely no action to be taken for the module.

**Comment by morgante** [comment]
Fortunately it looks like someone already opened the correct issue on the provider. Feel free to follow along there: https://github.com/terraform-providers/terraform-provider-google/issues/6295

**Comment by juan-vg** [comment]
@morgante My fault then. I've explained myself wrong. It started happening at the same time a new provider has been released.

I've tested this module against provider google-beta versions from 3.18 to 3.20. None work now. Yesterday 3.19 worked as a charm, not today. I'm editing the issue. Could you please be so kind to reopen it?

Beside the above, there were no code changes from my side. Just stopped working

**Comment by morgante** [comment]
There hasn't been any change to this module in 14 days. If your code was working yesterday but not today, it's a provider change.

**Comment by juan-vg** [comment]
@morgante I must apologize. I was setting the version for the google-beta provider. When I did the same for the google one everything started working again. You were completely right.

Sorry for the noise

**Comment by morgante** [comment]
No worries, thankfully I think a fix will be available in the next provider release.
